vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        vape_file:
            uri_prefix: /uploads/images/vape
            upload_destination: '%upload_directory%/images/vape'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
