vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        vape_file:
            uri_prefix: /uploads/images/vape
            upload_destination: '%kernel.project_dir%/public/images/vape'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
